// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc0uFv0zvwaBVgXqjECq8D1t4znTGgmC4',
    appId: '1:449813011479:web:b63035e9bf633c057c9052',
    messagingSenderId: '449813011479',
    projectId: 'where-is-it-d1e3c',
    authDomain: 'where-is-it-d1e3c.firebaseapp.com',
    storageBucket: 'where-is-it-d1e3c.firebasestorage.app',
    measurementId: 'G-5N5RLWQZEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACoAArV9oliPH3INgrTjM7LjsQlpXlTyc',
    appId: '1:449813011479:android:ed1bb8df50a99baf7c9052',
    messagingSenderId: '449813011479',
    projectId: 'where-is-it-d1e3c',
    storageBucket: 'where-is-it-d1e3c.firebasestorage.app',
  );

}